import { useState } from 'react'
import { supabase } from '../lib/supabaseClient'

export default function DiligentEffortStatement({ calculation }) {
  const [loading, setLoading] = useState(false)
  const [selectedState, setSelectedState] = useState(calculation.state)

  const generatePDF = async () => {
    setLoading(true)
    try {
      const stateNames = { 'CA': 'California', 'NY': 'New York', 'TX': 'Texas', 'FL': 'Florida' }
      const date = new Date().toLocaleDateString()
      
      let htmlContent = ''

      if (selectedState === 'CA') {
        htmlContent = `
          <h1 style="text-align:center;font-size:16px;margin-bottom:5px;">CALIFORNIA SURPLUS LINES ASSOCIATION</h1>
          <h2 style="text-align:center;font-size:14px;margin-top:0;">DILIGENT SEARCH REPORT (SL-2)</h2>
          <p style="text-align:center;font-weight:bold;">IMPORTANT: THIS FORM IS REQUIRED FOR ALL SURPLUS LINES PLACEMENTS</p>
          <h3 style="font-size:12px;margin-top:20px;">PRODUCER INFORMATION</h3>
          <p>Producer Name: ___________________________________________________</p>
          <p>Producer License #: ___________________________________________________</p>
          <h3 style="font-size:12px;">INSURED INFORMATION</h3>
          <p>Insured Name: ${calculation.policyholderName || '___________________________________________________'}</p>
          <p>Mailing Address: ___________________________________________________</p>
          <h3 style="font-size:12px;">COVERAGE INFORMATION</h3>
          <p>Type of Coverage: ___________________________________________________</p>
          <p>Policy Number: ${calculation.policyNumber || '___________________________________________________'}</p>
          <p>Effective Date: ${calculation.effectiveDate || '___________________________________________________'}</p>
          <p>Premium: $${calculation.premium.toFixed(2)}</p>
          <h3 style="font-size:12px;">DILIGENT SEARCH REQUIREMENTS</h3>
          <p>I hereby certify that I have made a thorough search of the admitted market and have requested quotations from at least THREE (3) admitted insurers for the coverage described above, and that each insurer has either declined the risk or refused to write it on reasonable terms and conditions.</p>
          <p><strong>List THREE Admitted Insurers Contacted and Declined:</strong></p>
          <p>1. Insurer: _________________________ Contact Date: _________ Reason: Declined / Not at Reasonable Rates</p>
          <p>2. Insurer: _________________________ Contact Date: _________ Reason: Declined / Not at Reasonable Rates</p>
          <p>3. Insurer: _________________________ Contact Date: _________ Reason: Declined / Not at Reasonable Rates</p>
          <p style="margin-top:20px;"><strong>CERTIFICATION:</strong> I certify under penalty of perjury under the laws of the State of California that the foregoing is true and correct.</p>
          <p style="margin-top:30px;">Producer Signature: _________________________ Date: __________</p>
          <p>Producer Printed Name: _________________________________</p>
          <p style="margin-top:40px;font-size:11px;color:#666;">Generated by E&S Calculator | ${date}</p>
        `
      } else if (selectedState === 'NY') {
        htmlContent = `
          <h1 style="text-align:center;font-size:14px;margin-bottom:5px;">STATE OF NEW YORK</h1>
          <h2 style="text-align:center;font-size:14px;margin-top:0;">AFFIDAVIT OF DILIGENT EFFORT</h2>
          <p style="text-align:center;margin-bottom:20px;"><strong>EXCESS LINES ASSOCIATION OF NEW YORK (ELANY)</strong></p>
          <p>I, the undersigned, being duly sworn, do hereby depose and say:</p>
          <p>1. That I am the insurance agent/broker representing the named insured in the procurement of insurance coverage for the risks described herein.</p>
          <p>2. <strong>INSURED:</strong> ${calculation.policyholderName || '________________________________'}</p>
          <p>3. <strong>POLICY NUMBER:</strong> ${calculation.policyNumber || '________________________________'}</p>
          <p>4. <strong>EFFECTIVE DATE:</strong> ${calculation.effectiveDate || '________________________________'}</p>
          <p>5. <strong>COVERAGE TYPE:</strong> ________________________________</p>
          <p>6. <strong>PREMIUM AMOUNT:</strong> $${calculation.premium.toFixed(2)}</p>
          <p>7. That I have made a diligent effort to procure the above-described insurance from authorized insurers and that such coverage is not available from any authorized insurer at reasonable rates.</p>
          <p>8. The following authorized insurers were contacted and declined coverage:</p>
          <p style="margin-left:40px;">A. Insurer Name: _________________________ Date: _________ Declination Reason: _____________________</p>
          <p style="margin-left:40px;">B. Insurer Name: _________________________ Date: _________ Declination Reason: _____________________</p>
          <p style="margin-left:40px;">C. Insurer Name: _________________________ Date: _________ Declination Reason: _____________________</p>
          <p>9. I further certify that the surplus lines insurer placed is licensed and eligible to write the above coverage.</p>
          <p style="margin-top:30px;">Signature: _________________________</p>
          <p>Printed Name: _________________________</p>
          <p>License Number: _________________________</p>
          <p>Date: _________________________</p>
          <p style="margin-top:40px;font-size:11px;">Generated by E&S Calculator | ${date}</p>
        `
      } else if (selectedState === 'TX') {
        htmlContent = `
          <h1 style="text-align:center;font-size:14px;margin-bottom:5px;">SURPLUS LINES STAMPING OFFICE OF TEXAS (SLTX)</h1>
          <h2 style="text-align:center;font-size:14px;margin-top:0;">TEXAS DILIGENT EFFORT AFFIDAVIT (Form 1.1)</h2>
          <p style="text-align:center;margin-bottom:20px;"><strong>Pursuant to Texas Insurance Code §981.004</strong></p>
          <h3 style="font-size:12px;">BROKER INFORMATION</h3>
          <p>Retail Broker Name: _________________________________</p>
          <p>Retail Broker License #: _________________________________</p>
          <p>Surplus Lines Broker Name: _________________________________</p>
          <p>Surplus Lines Broker License #: _________________________________</p>
          <p>Broker Type (Check One): ☐ Wholesale Broker  ☐ Managing General Agent</p>
          <h3 style="font-size:12px;">POLICY INFORMATION</h3>
          <p>Policy/Binder Number: ${calculation.policyNumber || '_________________________________'}</p>
          <p>Insured Name: ${calculation.policyholderName || '_________________________________'}</p>
          <p>Effective Date: ${calculation.effectiveDate || '_________________________________'}</p>
          <p>Premium Amount: $${calculation.premium.toFixed(2)}</p>
          <h3 style="font-size:12px;">DILIGENT EFFORT STATEMENT</h3>
          <p>I hereby certify that a diligent effort has been made to place the above-described insurance with authorized insurers operating in the State of Texas, and that coverage is not available from such insurers at reasonable rates and on reasonable terms and conditions.</p>
          <p><strong>Authorized Insurers Contacted:</strong></p>
          <p>Insurer 1: _________________________ Declined: Yes / No | Reason: _____________________</p>
          <p>Insurer 2: _________________________ Declined: Yes / No | Reason: _____________________</p>
          <p>Insurer 3: _________________________ Declined: Yes / No | Reason: _____________________</p>
          <p style="margin-top:20px;font-size:10px;color:#666;">*Exempt commercial purchasers need not provide evidence of diligent effort per TIC 981.0031</p>
          <p><strong>CERTIFICATION:</strong> I certify under penalty of perjury that the statements made herein are true and correct.</p>
          <p style="margin-top:30px;">Signature: _________________________ Date: __________</p>
          <p>Printed Name: _________________________________</p>
          <p style="margin-top:40px;font-size:10px;">File with SLTX or retain for audit</p>
          <p style="font-size:10px;">Generated by E&S Calculator | ${date}</p>
        `
      } else if (selectedState === 'FL') {
        htmlContent = `
          <h1 style="text-align:center;font-size:14px;margin-bottom:5px;">FLORIDA SURPLUS LINES SERVICE OFFICE (FSLSO)</h1>
          <h2 style="text-align:center;font-size:14px;margin-top:0;">STATEMENT OF DILIGENT EFFORT</h2>
          <div style="background:#ffffcc;padding:10px;border-left:3px solid #ff6600;margin:15px 0;">
            <p style="margin:0;font-size:11px;"><strong>IMPORTANT NOTICE:</strong> Effective July 1, 2025, Florida has eliminated the diligent effort requirement. This form is provided for compliance during the transition period.</p>
          </div>
          <h3 style="font-size:12px;">PRODUCING AGENT INFORMATION</h3>
          <p>Producing Agent Name: _________________________________</p>
          <p>License Number: _________________________________</p>
          <p>Agency Name: _________________________________</p>
          <h3 style="font-size:12px;">INSURED INFORMATION</h3>
          <p>Insured Name: ${calculation.policyholderName || '_________________________________'}</p>
          <p>Address: _________________________________</p>
          <h3 style="font-size:12px;">COVERAGE SOUGHT</h3>
          <p>Type of Coverage: _________________________________</p>
          <p>Policy Number: ${calculation.policyNumber || '_________________________________'}</p>
          <p>Effective Date: ${calculation.effectiveDate || '_________________________________'}</p>
          <p>Premium Amount: $${calculation.premium.toFixed(2)}</p>
          <h3 style="font-size:12px;">DILIGENT EFFORT DOCUMENTATION</h3>
          <p>I certify that I have made a diligent effort to procure the above-described insurance coverage from authorized Florida insurers and that the full amount of insurance required is not procurable from such authorized insurers.</p>
          <p><strong>Authorized Insurers Contacted and Their Response:</strong></p>
          <p>1. Insurer: _________________________ Date: _________ Response: Declined / Incomplete Quotes</p>
          <p>2. Insurer: _________________________ Date: _________ Response: Declined / Incomplete Quotes</p>
          <p>3. Insurer: _________________________ Date: _________ Response: Declined / Incomplete Quotes</p>
          <p><strong>Reason Coverage Unavailable:</strong></p>
          <p>_________________________________________________________________</p>
          <p style="margin-top:20px;"><strong>CERTIFICATION:</strong> Under penalty of perjury, I certify the facts stated herein are true, correct, and complete.</p>
          <p style="margin-top:30px;">Agent Signature: _________________________ Date: __________</p>
          <p>Agent Printed Name: _________________________________</p>
          <p style="margin-top:40px;font-size:11px;">Generated by E&S Calculator | ${date}</p>
        `
      }

      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        await supabase.from('diligent_effort_statements').insert([{user_id:user.id,state:selectedState,policyholder_name:calculation.policyholderName,policy_number:calculation.policyNumber,premium:calculation.premium}]).catch(e=>console.log('Save error:',e))
      }

      const element = document.createElement('div')
      element.innerHTML = `<div style="font-family:Arial;padding:20px;line-height:1.6;font-size:12px;">${htmlContent}</div>`
      
      const script = document.createElement('script')
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js'
      document.head.appendChild(script)
      
      script.onload = () => {
        const opt = {
          margin: 15,
          filename: `Diligent-Effort-${stateNames[selectedState]}-${calculation.policyholderName || 'Statement'}.pdf`,
          image: { type: 'jpeg', quality: 0.98 },
          html2canvas: { scale: 2 },
          jsPDF: { orientation: 'portrait', unit: 'mm', format: 'a4' }
        }
        html2pdf().set(opt).from(element).save()
      }
    } catch (e) {
      console.error('Error:', e)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{marginTop:'20px',padding:'16px',background:'#f9f9f9',borderRadius:'6px',border:'2px solid #0E6E5C'}}>
      <h4 style={{marginBottom:'16px',color:'#0E6E5C'}}>📋 State-Specific Diligent Effort Form</h4>
      <p style={{color:'#666',fontSize:'13px',marginBottom:'16px'}}>Select your state to generate the required compliance form.</p>
      
      <div style={{marginBottom:'16px'}}>
        <label style={{display:'block',marginBottom:'6px',fontWeight:'bold',fontSize:'12px'}}>Select State:</label>
        <select value={selectedState} onChange={(e)=>setSelectedState(e.target.value)} style={{width:'100%',padding:'10px',border:'1px solid #0E6E5C',borderRadius:'4px',fontSize:'14px',fontWeight:'bold'}}>
          <option value="CA">California (SL-2 Form)</option>
          <option value="NY">New York (Affidavit)</option>
          <option value="TX">Texas (SLTX Form 1.1)</option>
          <option value="FL">Florida (FSLSO Statement)</option>
        </select>
      </div>

      <div style={{background:'white',padding:'12px',borderRadius:'4px',marginBottom:'16px',borderLeft:'3px solid #0E6E5C'}}>
        {selectedState === 'CA' && <p style={{margin:'0',fontSize:'12px',color:'#333'}}><strong>California:</strong> Requires 3 admitted insurer declinations. File with CA Surplus Lines Association within 60 days.</p>}
        {selectedState === 'NY' && <p style={{margin:'0',fontSize:'12px',color:'#333'}}><strong>New York:</strong> Affidavit attesting to diligent effort with declinations. Submit to ELANY.</p>}
        {selectedState === 'TX' && <p style={{margin:'0',fontSize:'12px',color:'#333'}}><strong>Texas:</strong> Official form per Insurance Code §981.004. File with or retain for SLTX audit.</p>}
        {selectedState === 'FL' && <p style={{margin:'0',fontSize:'12px',color:'#333'}}><strong>Florida:</strong> Diligent effort requirement ending July 1, 2025. Use for compliance transition.</p>}
      </div>

      <button onClick={generatePDF} disabled={loading} style={{width:'100%',padding:'10px',background:loading?'#ccc':'#0E6E5C',color:'white',border:'none',borderRadius:'4px',fontWeight:'bold',cursor:loading?'not-allowed':'pointer',fontSize:'14px'}}>
        {loading?'Generating...':'📄 Generate State-Specific Form'}
      </button>
    </div>
  )
}
