import { useState } from 'react'
import { supabase } from '../lib/supabaseClient'

export default function DiligentEffortStatement({ calculation }) {
  const [loading, setLoading] = useState(false)
  const [declinations, setDeclinations] = useState('3')

  const generatePDF = async () => {
    setLoading(true)
    try {
      const html = `<html><head><title>Diligent Effort Statement</title><style>body{font-family:Arial;padding:30px;line-height:1.6;}h1{text-align:center;color:#0E6E5C;margin-bottom:30px;}.field{margin-bottom:15px;}.label{font-weight:bold;}.value{border-bottom:1px solid #000;padding:5px 0;min-height:20px;}.sig-area{margin-top:40px;}.sig-line{border-top:1px solid #000;width:200px;margin-top:30px;font-size:12px;}</style></head><body><h1>STATEMENT OF DILIGENT EFFORT</h1><p>I hereby certify that I have made a diligent effort to procure the insurance coverage described herein from insurers authorized to transact insurance in my state, and that such coverage is not available from any authorized insurer at a reasonable rate and on reasonable terms.</p><div class="field"><div class="label">Policyholder Name:</div><div class="value">${calculation.policyholderName || ''}</div></div><div class="field"><div class="label">Policy Number:</div><div class="value">${calculation.policyNumber || ''}</div></div><div class="field"><div class="label">Effective Date:</div><div class="value">${calculation.effectiveDate || ''}</div></div><div class="field"><div class="label">State:</div><div class="value">${calculation.state}</div></div><div class="field"><div class="label">Coverage Description:</div><div class="value">Surplus Lines Insurance</div></div><div class="field"><div class="label">Premium Amount:</div><div class="value">$${calculation.premium.toFixed(2)}</div></div><p style="margin-top:30px;"><strong>Declaration of Diligent Search:</strong></p><p>I certify that I have contacted the following authorized insurers and made good faith solicitations for coverage:</p><ol><li>Authorized Insurer #1: ________________________________ (Declination: Yes / No)</li><li>Authorized Insurer #2: ________________________________ (Declination: Yes / No)</li><li>Authorized Insurer #3: ________________________________ (Declination: Yes / No)</li></ol><p>The above-named authorized insurers have either declined to insure the risk or refused to provide coverage on reasonable terms, making it necessary to place this coverage with a surplus lines insurer.</p><p style="margin-top:30px;margin-bottom:10px;"><strong>Broker Certification:</strong></p><p>I further certify under penalty of perjury that the foregoing facts are true and correct to the best of my knowledge and belief.</p><div class="sig-area"><div style="margin-bottom:40px;">Broker/Agent Signature: _____________________________</div><div class="sig-line">Date</div></div><p style="margin-top:40px;font-size:11px;color:#666;">Generated by E&S Calculator | ${new Date().toLocaleDateString()}</p></body></html>`

      const { data: { user } } = await supabase.auth.getUser()
      if (user) {
        await supabase.from('diligent_effort_statements').insert([{user_id:user.id,state:calculation.state,policyholder_name:calculation.policyholderName,policy_number:calculation.policyNumber,premium:calculation.premium}]).catch(e=>console.log('Save error:',e))
      }

      const script = document.createElement('script')
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js'
      document.head.appendChild(script)
      script.onload = () => {
        html2pdf().set({margin:15,filename:`Diligent-Effort-${calculation.policyholderName || 'Statement'}.pdf`,html2canvas:{scale:2},jsPDF:{orientation:'portrait',unit:'mm',format:'a4'}}).from(html).save()
      }
    } catch (e) {
      console.error('Error:', e)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{marginTop:'20px',padding:'16px',background:'#f9f9f9',borderRadius:'6px',border:'2px solid #0E6E5C'}}>
      <h4 style={{marginBottom:'16px',color:'#0E6E5C'}}>📋 Diligent Effort Statement</h4>
      <p style={{color:'#666',fontSize:'14px',marginBottom:'16px'}}>Generate a generic diligent effort statement for compliance filing.</p>
      <button onClick={generatePDF} disabled={loading} style={{width:'100%',padding:'10px',background:loading?'#ccc':'#0E6E5C',color:'white',border:'none',borderRadius:'4px',fontWeight:'bold',cursor:loading?'not-allowed':'pointer',fontSize:'14px'}}>
        {loading?'Generating...':'📄 Generate Diligent Effort Statement'}
      </button>
    </div>
  )
}
